services:
  ticketlemon_app:
    build: .
    ports:
      - "80:80"
    environment:
      - DB_HOST=ticketlemon_db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ticketlemon
      - REDIS_HOST=redis
    depends_on:
      - ticketlemon_db
      - ticketlemon_redis
    volumes:
      - .:/app
  ticketlemon_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ticketlemon
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  ticketlemon_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: ticketlemon_db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - ticketlemon_db
  ticketlemon_redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  ticketlemon_data:
    driver: local
